# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    xarm6_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    xarm_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

xarm6_controller:
  ros__parameters:
    joints:
      - xarm_joint1
      - xarm_joint2
      - xarm_joint3
      - xarm_joint4
      - xarm_joint5
      - xarm_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: false
xarm_gripper_controller:
  ros__parameters:
    joint: xarm_gripper_drive_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0