sensors:
  # - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  #   point_cloud_topic: /CHARMIE/D455_head/depth/color/points
  #   max_range: 3.0
  #   point_subsample: 1
  #   padding_offset: 0.01
  #   padding_scale: 1.0
  #   filtered_cloud_topic: filtered_cloud
  #   max_update_rate: 5.0
  #   observation_sources: head_camera_sensor

  #   head_camera_sensor:
  #     sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  #     point_cloud_topic: /CHARMIE/D455_head/depth/color/points
  #     max_range: 3.0
  #     point_subsample: 1
  #     data_type: PointCloud2
  #     frame_subsample: 1
  #     skip_octomap_update: false
  #     enabled: true

    - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
      point_cloud_topic: /CHARMIE/D455_head/depth/color/points
      max_range: 3.0
      point_subsample: 1
      padding_offset: 0.01
      padding_scale: 1.0
      filtered_cloud_topic: filtered_cloud_head
      max_update_rate: 5.0
      ns: head_camera_sensor

    - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
      point_cloud_topic: /CHARMIE/D455_hand/depth/color/points
      max_range: 2.0
      point_subsample: 1
      padding_offset: 0.01
      padding_scale: 1.0
      filtered_cloud_topic: filtered_cloud_hand
      max_update_rate: 5.0
      ns: hand_camera_sensor